<?php

namespace Devlin\ModelAnalyzer\Tests\Unit;

use Devlin\ModelAnalyzer\Schema\SchemaSnapshot;
use Devlin\ModelAnalyzer\Support\DefinitionsGenerator;
use Devlin\ModelAnalyzer\Support\DocsGenerator;
use Devlin\ModelAnalyzer\Tests\TestCase;

/**
 * Markdown anchors are generated by the renderer from the heading text, so a
 * table-of-contents link only works if it reproduces that slug exactly.
 * GitHub's algorithm lowercases, strips punctuation other than hyphens and
 * underscores, and turns spaces into hyphens — underscores are preserved.
 */
class DocsAnchorTest extends TestCase
{
    /**
     * @param  string[] $tables
     * @return SchemaSnapshot
     */
    private function snapshotWith(array $tables)
    {
        $snapshot = new SchemaSnapshot('test');

        foreach ($tables as $table) {
            $snapshot->ensureTable($table);
            $snapshot->tables[$table]['columns'] = [
                'id' => ['name' => 'id', 'type' => 'bigint', 'nullable' => false, 'key' => 'PRI', 'default' => null],
            ];
        }

        return $snapshot;
    }

    public function test_underscored_table_names_link_to_the_heading_anchor()
    {
        $md = (new DocsGenerator())->generateMarkdown($this->snapshotWith(['activity_list']));

        $this->assertStringContainsString('- [activity_list](#activity_list)', $md);
        $this->assertStringContainsString('## activity_list', $md);

        // The old, broken form must be gone.
        $this->assertStringNotContainsString('#table-activity-list', $md);
    }

    public function test_every_toc_link_resolves_to_a_heading()
    {
        $tables = ['activity_list', 'orders', 'order_product', 'users', 'oauth_access_tokens'];

        $md = (new DocsGenerator())->generateMarkdown($this->snapshotWith($tables));

        preg_match_all('/^- \[.+?\]\(#(.+?)\)$/m', $md, $links);
        $this->assertNotEmpty($links[1], 'expected table-of-contents links');

        foreach ($links[1] as $anchor) {
            $this->assertContains(
                $anchor,
                $this->headingSlugs($md),
                sprintf('TOC anchor "#%s" does not match any heading', $anchor)
            );
        }
    }

    public function test_uppercase_table_names_are_lowercased_in_the_anchor()
    {
        $md = (new DocsGenerator())->generateMarkdown($this->snapshotWith(['ActivityList']));

        $this->assertStringContainsString('- [ActivityList](#activitylist)', $md);
    }

    public function test_html_ids_match_their_own_links()
    {
        $html = (new DocsGenerator())->generateHtml($this->snapshotWith(['activity_list', 'orders']));

        preg_match_all('/href="#([^"]+)"/', $html, $hrefs);
        preg_match_all('/id="([^"]+)"/', $html, $ids);

        $this->assertNotEmpty($hrefs[1]);

        foreach ($hrefs[1] as $href) {
            $this->assertContains($href, $ids[1], sprintf('href "#%s" has no matching id', $href));
        }
    }

    public function test_definitions_html_ids_use_the_same_slug()
    {
        $html = (new DefinitionsGenerator())->generateHtml($this->snapshotWith(['activity_list']));

        $this->assertStringContainsString('id="activity_list"', $html);
    }

    /**
     * Slugs a Markdown renderer would derive from the `##` headings.
     *
     * @param  string $markdown
     * @return string[]
     */
    private function headingSlugs($markdown)
    {
        preg_match_all('/^## (.+)$/m', $markdown, $headings);

        return array_map(function ($heading) {
            $slug = strtolower(trim($heading));
            $slug = preg_replace('/[^\p{L}\p{N}\s_-]+/u', '', $slug);

            return preg_replace('/\s+/', '-', $slug);
        }, $headings[1]);
    }
}
